from datetime import datetime, timezone
from ..database import db


class Product(db.Model):
    __tablename__ = "products"

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255), nullable=False)
    description = db.Column(db.Text)
    supplier_url = db.Column(db.String(500))
    supplier_id = db.Column(db.Integer, db.ForeignKey("suppliers.id"), nullable=True)
    cost_price = db.Column(db.Float, default=0.0)
    sell_price = db.Column(db.Float, default=0.0)
    margin_pct = db.Column(db.Float, default=0.0)
    category = db.Column(db.String(100))
    # active | testing | killed | unlisted
    status = db.Column(db.String(20), default="testing")
    supplier_stock = db.Column(db.Integer, default=0)
    sku = db.Column(db.String(100))
    image_url = db.Column(db.String(500))
    # Generated by MarketingContentAgent
    ad_copy = db.Column(db.Text)
    seo_description = db.Column(db.Text)
    created_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))
    updated_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc),
                           onupdate=lambda: datetime.now(timezone.utc))

    order_items = db.relationship("OrderItem", backref="product", lazy=True)

    def margin(self):
        if self.sell_price and self.cost_price:
            return round((self.sell_price - self.cost_price) / self.sell_price * 100, 2)
        return 0.0

    def to_dict(self):
        return {
            "id": self.id,
            "title": self.title,
            "cost_price": self.cost_price,
            "sell_price": self.sell_price,
            "margin_pct": self.margin(),
            "status": self.status,
            "supplier_stock": self.supplier_stock,
            "category": self.category,
            "image_url": self.image_url,
        }


class ProductResearch(db.Model):
    __tablename__ = "products_research"

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255), nullable=False)
    aliexpress_url = db.Column(db.String(500))
    cost_price = db.Column(db.Float, default=0.0)
    estimated_sell_price = db.Column(db.Float, default=0.0)
    estimated_margin = db.Column(db.Float, default=0.0)
    trend_score = db.Column(db.Float, default=0.0)
    search_volume = db.Column(db.Integer, default=0)
    aliexpress_orders = db.Column(db.Integer, default=0)
    competition_level = db.Column(db.String(20), default="unknown")  # low/medium/high
    recommended = db.Column(db.Boolean, default=False)
    niche = db.Column(db.String(100))
    notes = db.Column(db.Text)
    created_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))

    def to_dict(self):
        return {
            "id": self.id,
            "title": self.title,
            "cost_price": self.cost_price,
            "estimated_sell_price": self.estimated_sell_price,
            "estimated_margin": self.estimated_margin,
            "trend_score": self.trend_score,
            "aliexpress_orders": self.aliexpress_orders,
            "competition_level": self.competition_level,
            "recommended": self.recommended,
            "niche": self.niche,
            "created_at": self.created_at.isoformat(),
        }
